baseURL = "https://cranky-williams-5827e9.netlify.app"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "5"
theme = "persian-hugo"
title = "Ponder"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Portfolio"
url = "https://www.atomicpx.com"
weight = 3
[[menu.main]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 6
[[menu.main]]
name = "Contact"
url = "contact"
weight = 5
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "<a href=\"https://www.atomicpx.com\">atomic</a>"
description = "A Blog For Thoughts"
logo = "images/ponder-logo3.png"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
